language: cpp
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
      - tobydox/mingw-x-precise
    packages:
      - cmake
      - cmake-data
      - g++-5
      - gcc-5

before_install:
  - sudo apt-get install mingw-w64
  - sudo add-apt-repository ppa:tobydox/mingw-w64 -y
  - sudo apt-get update -y

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build && cd build && cmake .. && make && make test && cd ..
  - mkdir build_win && cd build_win && cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/Toolchain-mingw64.cmake && make && cd ..
