language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - g++-5
      - gcc-5

script:
  - mkdir build && cd build && cmake .. && make && make test
