version: 2
general:
dependencies:
  cache_directories:
    - ~/cmake-3.10.3
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/lib-ledger-core
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
      - run:
          command: |
            . .circleci/cmake-install.sh
      - run:
          name: initialize submodules
          command: git submodule update --init --recursive
      - run:
          command: |
            . .circleci/build_lib.sh
      - run:
          name: build module
          command: yarn
      - run:
          name: test
          command: |
              node index.js && node sample/wallet_pool_test.js
      - run:
          name: run tests
          command: |
              cd ../lib-ledger-core-build
              ctest
      - run:
          command: |
              mkdir -p /tmp/core_dumps
              cp ./sample/tmp/log_file_test_instance-l.log /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - run:
          command: |
              mkdir -p /tmp/lib
              cp ../lib-ledger-core-build/core/src/libledger-core.so /tmp/lib
      - store_artifacts:
          path: /tmp/lib
      - run:
          command: |
              mkdir -p /tmp/node_module
              cp ./build/Release/ledgerapp_nodejs.node /tmp/node_module
      - store_artifacts:
          path: /tmp/node_module
      - deploy:
                name: Deploy to s3 bucket
                command: |
                  aws s3 sync ../lib-ledger-core-build/core/src/ s3://ledger-lib-ledger-core/ --acl public-read --exclude "CMakeFiles/*" --exclude "MakeFile" --exclude "cmake_install.cmake" && \
                  aws s3 ls s3://ledger-lib-ledger-core/;